name: Flutter CI - Auto Migration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0' # Specify your Flutter version

    - name: Create a New Flutter Project
      run: |
        flutter create -t app new_project
        cp -r lib new_project/lib
        cp pubspec.yaml new_project/
        if [ -d assets ]; then cp -r assets new_project/assets; fi

    - name: Install dependencies in New Project
      working-directory: new_project
      run: flutter pub get

    - name: Build APK
      working-directory: new_project
      run: flutter build apk --release

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: new_project/build/app/outputs/flutter-apk/app-release.apk
