name: Flutter CI - Auto Migration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2.16.0
      with:
        flutter-version: '3.13.0'

    - name: List contents of the repository
      run: |
        echo "Current directory contents:"
        ls -la

    - name: Create a New Flutter Project
      run: |
        flutter create -t app new_project
        cp -r lib new_project/lib
        cp pubspec.yaml new_project/
        if [ -d assets ]; then
          cp -r assets new_project/assets
        fi
        if [ -d android ]; then
          cp -r android new_project/android
        fi
        if [ -d ios ]; then
          cp -r ios new_project/ios
        fi
        if [ -d test ]; then
          cp -r test new_project/test
        fi

    - name: List contents of new_project directory
      run: |
        echo "new_project directory contents:"
        ls -la new_project

    - name: Install dependencies in New Project
      working-directory: new_project
      run: flutter pub get

    - name: Migrate to Android embedding v2
      working-directory: new_project
      run: flutter create --platforms=android .

    - name: Build APK
      working-directory: new_project
      run: flutter build apk --release

    - name: List contents of build directory
      run: |
        echo "Build directory contents:"
        ls -la new_project/build/app/outputs/flutter-apk

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: new_project/build/app/outputs/flutter-apk/app-release.apk
