name: Build Flutter APK

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the workflow
  pull_request:
    branches:
      - main  # You can change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.1'  # Specify the Flutter version you want to use

    - name: Install dependencies
      run: flutter pub get

    - name: Migrate to Android embedding v2
      run: flutter create --platforms=android .

    - name: Build APK
      run: flutter build apk --debug  # Use --release for release builds

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: build/app/outputs/flutter-apk/app-debug.apk
